name: Build and Deploy VectorSynth

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '**/docs/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '**/docs/**'

env:
  REGISTRY: ghcr.io/terratensor
  REGISTRY_HOST: ghcr.io
  HOST: ${{ secrets.PRODUCTION_HOST }}
  PORT: ${{ secrets.PRODUCTION_PORT || '22' }}
  DEPLOY_DIR: /home/deploy/vectorsynth
  STACK_NAME: vectorsynth
  IMAGE_NAME: vectorsynth

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inject branch slug
        uses: rlespinasse/github-slug-action@v5

      - name: Set image tag
        run: |
          if [ "$GITHUB_REF" = "refs/heads/main" ]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${GITHUB_REF_SLUG}-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push VectorSynth image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRODUCTION_KEY }}
          known_hosts: ${{ secrets.PRODUCTION_KNOWN_HOSTS }}

      - name: Prepare docker-compose.yml
        run: |
          export REGISTRY=${{ env.REGISTRY }}
          export IMAGE_NAME=${{ env.IMAGE_NAME }}
          export IMAGE_TAG=${{ env.IMAGE_TAG }}
          envsubst < docker-compose.yml > docker-compose-env.yml
          cat docker-compose-env.yml

      - name: Copy files to server
        run: |
          scp -o StrictHostKeyChecking=no -P ${{ env.PORT }} docker-compose-env.yml deploy@${{ env.HOST }}:${{ env.DEPLOY_DIR }}/docker-compose.yml
          rm -f docker-compose-env.yml

      - name: Deploy to Docker Swarm
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ env.PORT }} deploy@${{ env.HOST }} "
            cd ${{ env.DEPLOY_DIR }} && \
            docker stack deploy -c docker-compose.yml ${{ env.STACK_NAME }} --with-registry-auth && \
            sleep 10 && \
            docker service ls --filter \"name=${{ env.STACK_NAME }}_\" --format \"table {{.Name}}\t{{.Image}}\t{{.Replicas}}\"
          "